# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'http://www.google.com/'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev!
  
  deploy-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
      url: 'http://www.google.com/'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy Hmg
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'http://www.google.com/'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy Prd
